# Generated by Django 3.2.4 on 2021-06-11 13:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CV_Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=64)),
                ('company', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=500)),
                ('status', models.IntegerField(choices=[(1, 'Application Sent'), (2, 'Application Viewed'), (3, 'Application is examined'), (4, 'Recruitment in progress'), (5, 'Hired'), (6, 'Rejected'), (7, 'Offer declined'), (8, 'No response from the company')], default=1)),
                ('date', models.DateField(default=datetime.date.today)),
                ('method', models.CharField(blank=True, choices=[('Direct Mail', 'Direct Mail'), ('LinkedIn', 'LinkedIn'), ('JustJoinIT', 'JustJoinIT'), ('No Fluff Jobs', 'No Fluff Jobs'), ('Other', 'Other')], max_length=64)),
                ('remote', models.BooleanField()),
                ('comment', models.TextField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
